import ClientComponent from './ClientComponent'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClientComponent />
      <body>{children}</body>
    </html>
  )
}
